## Prática

Este notebook serve para você praticar o que viu no livro.

Pode haver mais de uma maneira diferente de completar um exercício.

Os exercícios são baseados no conteúdo do livro.

Para mais referências e recursos, fica a sugestão de consultar a [documentação do NumPy.](https://numpy.org/devdocs/user/index.html)

In [1]:
# Importe o numpy, utilize a abreviação 'np'
import numpy as np

Em vetores unidimensionais, utilizamos somente um par de colchetes. Para duas, dois pares e assim sucessivamente. 
1) Monte o array desejado.
2) Se houver apenas uma dimensão, apenas abra e feche o par de colchetes.
3) Se não, os pares de colchetes devem ter o mesmo número de dimensões do array.

In [38]:
# Utilizando np.array() crie:
# 1 array unidimensional "vetor"
array1 = np.array([1,2,3])

# 1 array de duas dimensões "matrix"
array2 = np.array([[1,2,3], [4,5,6]])

# 1 array de três dimensões
array3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])

* Por que ele só imprime, sem print, o último comando informado? 

In [32]:
# Liste os atributos de todos os arrays criados anteriormente
# número de dimensões, tipo de dado, tamanho
print(array1)
print(array1.ndim)
print(type(array1))
print(array1.size)
array1.shape

[1 2 3]
1
<class 'numpy.ndarray'>
3


(3,)

In [33]:
# Liste os atributos de todos os arrays criados anteriormente
# número de dimensões, tipo de dado, tamanho
print(array2)
print(array2.ndim)
print(type(array2))
print(array2.size)
array2.shape

[[1 2 3]
 [4 5 6]]
2
<class 'numpy.ndarray'>
6


(2, 3)

In [39]:
# Liste os atributos de todos os arrays criados anteriormente
# número de dimensões, tipo de dado, tamanho
print(array3)
print(array3.ndim)
print(type(array3))
print(array3.size)
array3.shape

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
3
<class 'numpy.ndarray'>
9


(1, 3, 3)

Quando falar em array, estamos tratando de uma estrutura unimdimensional onde os valores se referem a (número de linhas, número de elementos por linha)

In [57]:
# Crie um array de números 1 de shape (10, 2)
array4 = np.ones((10,2))
print(array4)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


Para criar uma estrutura que solicite 3 elementos para o shape, teremos (camadas, linhas, colunas). 

As camadas são o número de arrays dentro de cada array.

In [54]:
# Crie um array (matriz) de zeros de shape (5, 4, 3)
array5 = np.zeros((5,4,3))
array5.shape
array5


array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

* Qual a lógica da utilização de únicos ou múltiplos parênteses?

Para se criar uma estrutura repetitiva que faça uma quantidade de valores, é necessário usar a função arange. Ela tem formato (0, 100, 3). Onde (início, fim, step). Aqui ele criará um array de 0 a 100 pulando de 3 em 3 valores.

In [58]:
# Crie um array com um range entre 0 e 100 e com step 3
rangeA5 = np.arange(0, 100, 3)
rangeA5

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

Para criar um array de valores aleatórios, é necessário que utilizemos a função random e randint (porque queremos criar com valores inteiros). Depois, indicamos o alcance do número de valores aleatórios que queremos gerar. Por fim, usamos o size para indicar qual o formato do array randômico que estamos criando.

Assim, a chamada da função random fica np.random.randint(alcance, formato do array(linhas, número de elementos por linha))

In [62]:
# Crie um array random (com elementos aleatórios) entre 0 e 10 de tamanho (7, 2)
randomA6 = np.random.randint(10, size = (7, 2))
randomA6

array([[2, 5],
       [6, 0],
       [3, 2],
       [8, 2],
       [9, 4],
       [4, 0],
       [3, 2]])

In [66]:
# Crie um array random float com elementos entre 0 e 1 com shape (5, 3)
randomA7 = np.random.random((5,3))
randomA7

array([[0.53238594, 0.86288317, 0.5652944 ],
       [0.10191346, 0.52422438, 0.95534906],
       [0.65058655, 0.76330863, 0.43896899],
       [0.01779721, 0.98444444, 0.67263693],
       [0.4843829 , 0.09785082, 0.8763856 ]])

Como os valores gerados anteriormente podem ser considerados aleatórios por não parecerem esteticamente harmônicos, existe a função seed, que permite criar elementos aleatórios predeterminados. A função seed é fortemente utilizada para experimentos em machine learning pela necessidade da consistência entre os dados.

* Como essas linhas de código interagem entre si? Como é possível não atribuir o valor a uma variável ou utilizá-la na declaração ou chamada da função rand, mas o valor ficar restrito na seed 42?

In [70]:
# Utilize  o seed com valor 42 e crie um array de números aleatórios entre 0 e 10 de tamanho (5, 3)
np.random.seed(42)
arrayA8 = np.random.randint(10, size = (5,3))

arrayA8


array([[6, 3, 7],
       [4, 6, 9],
       [2, 6, 7],
       [4, 3, 7],
       [7, 2, 5]])

Em estruturas unidimensionais, chamar o elemento na posição 0, trará o valor do primeiro número do nosso vetor.

In [71]:
# Selecione o primeiro elemento do último array que você criou
array1[0]

1

Em estruturas multidimensionais, chamar a posição 0 de uma matriz, trará a sua primeira linha. Para obter o elemento da primeira posição da primeira linha é necessário usar arrayA8[0,0].

* Por quê?

In [72]:
# Selecione a primeira linha do último array criado
arrayA8[0]

array([6, 3, 7])

* No caso, meu último array criado tem 3 elementos por linha, isso significa que não terei como pegar o quarto. Existe alguma forma de fazer isso utilizando o numpy?

In [77]:
# Selecione do primeiro até o quarto elemento da primeira linha do último array criado
rangeA5[0:4]

array([0, 3, 6, 9])

In [83]:
# Crie um novo array usando 'ones' com shape (3, 5)
array_ones = np.ones((3,5))
array_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

* Para operações entre matrizes, elas devem possuir o mesmo shape? 

In [91]:
# Subtraia o novo array de outro com dados aleatórios e armazene o resultado em uma variável chamada 'matrix'
array_random = np.random.randint(2, size = (3,5))

matrix = array_ones - array_random

print(matrix)

[[0. 0. 1. 1. 1.]
 [1. 0. 1. 1. 1.]
 [1. 1. 0. 1. 0.]]


In [93]:
# Encontre a média usando 'np.mean()' do valores no novo array chamado 'matrix'

np.mean(matrix)

0.6666666666666666

A transposição inverte a estrutura do array. Se ele tiver 3 linhas e 5 colunas, passa a ter o contrário, 5 linhas e 3 colunas.

In [94]:
# Faça a transposição da 'matrix', usando o método '.T'
matrix.T

array([[0., 1., 1.],
       [0., 0., 1.],
       [1., 1., 0.],
       [1., 1., 1.],
       [1., 1., 0.]])